In [1]:
import qTools.QuantumToolbox.states as qStates

# How-to-use functions in states.py of QuantumToolbox
---

Each example is introduced in the order that the functions appear inside the file

In [2]:
# Uncomment any (or both) of these two to print module docstrings
#print(qStates.__doc__)
help(qStates)

Help on module qTools.QuantumToolbox.states in qTools.QuantumToolbox:

NAME
    qTools.QuantumToolbox.states - Module of functions to create and/or normalise quantum states.

DESCRIPTION
    Functions
    -------
    :basis : Creates a `ket` state for a given dimension with 1 at a given row
    :completeBasis : Creates a complete basis of `ket` states
    :basisBra : Creates a `bra` state for a given dimension with 1 at a given column
    :zeros : Creates a column matrix (ket) of zeros
    :superPos : Creates a `ket` superposition state
    
    :densityMatrix : Converts a `ket` state into ``density matrix``
    :completeBasisMat : Creates a complete basis of ``density matrices`` or convert a ``ket basis`` to ``density matrix``
    
    :normalise : Function to normalise `any` state (ket or density matrix)
    :normaliseKet : Function to normalise `ket` state
    :normaliseMat : Function to normalise a ``density matrix``
    
    :compositeState : Function to create ``composite ket`` s

## basis
---
This is a method to create ket states for a given dimension with 1 at a given row.

In [3]:
# sparse=True by default
# for dimension 2 and 1 at 0th element of the column matrix (see the print below)
ketStateSparse = qStates.basis(dimension=2, state=0)
ketStateArray = qStates.basis(2, 0, sparse=False)

print('Sparse ket')
print(ketStateSparse)
# You obtain the array by simply calling .A on the sparse matrix
# If sparse=True, function simply returns state.A
# so, these two are equivalent
print('Array from Sparse ket')
print(ketStateSparse.A)
print('Array from basis function by sparse=False')
print(ketStateArray)

Sparse ket
  (0, 0)	1
Array from Sparse ket
[[1]
 [0]]
Array from basis function by sparse=False
[[1]
 [0]]


## completeBasis
---
This is a method to create a complete basis of ket states for a given dimension.

In [4]:
completeBasisSparse = qStates.completeBasis(2)
completeBasisArray = qStates.completeBasis(2, sparse=False)

print('Sparse kets of the complete basis and array (.A) for each')
for state in completeBasisSparse:
    print(state)
    print(state.A)
print('Array kets of the complete basis')
for state in completeBasisArray:
    print(state)

Sparse kets of the complete basis and array (.A) for each
  (0, 0)	1
[[1]
 [0]]
  (1, 0)	1
[[0]
 [1]]
Array kets of the complete basis
[[1]
 [0]]
[[0]
 [1]]


## basisBra
---
This is a method to create bra states for a given dimension.

In [5]:
# for dimension 2 and 1 at 1st element of the row matrix (see the print below)
braStateSparse = qStates.basisBra(dimension=2, state=1)
braStateArray = qStates.basisBra(2, 1, sparse=False)

print('Sparse Bra and array (.A) from the sparse Bra')
print(braStateSparse)
print(braStateSparse.A)
print('Array Bra from basisBra function by sparse=False')
print(braStateArray)

Sparse Bra and array (.A) from the sparse Bra
  (0, 1)	1
[[0 1]]
Array Bra from basisBra function by sparse=False
[[0 1]]


## zeros
---
This is a method to create a column matrix of zeros for a given dimension.

In [6]:
# for dimension 2 and all the elements of the column matrix are 0 (see the print below)
zerosSparse = qStates.zeros(2)
zerosArray = qStates.zeros(2, False)

print('Sparse zeros (ket) and array (.A) from the sparse Bra')
print(zerosSparse)
print(zerosSparse.A)
print('Array zeros (ket) from basisBra function by sparse=False')
print(zerosArray)

Sparse zeros (ket) and array (.A) from the sparse Bra
  (0, 0)	0
[[0]
 [0]]
Array zeros (ket) from basisBra function by sparse=False
[[0]
 [0]]


## superPos
---
This is a method to create a super-position state for a given dimension.
Depending on the second argument, this returns:

1) int: equivalent to basis, i.e. returns a ket state with a unit population at the given int 

2) list: creates an equally populated super-position state from a list of integers

3) dict: creates a super-position by using the key as state int and the value as population

In [7]:
# 1 at 0th element of the column matrix (see the print below)
superPosState0Sparse = qStates.superPos(dimension=2, excitations=1, sparse=True)
superPosState0Array = qStates.superPos(dimension=2, excitations=1, sparse=False)
# sqrt(0.5) at 0th and 1st elements of the column matrix, i.e. population of each state is 0.5
superPosState1Sparse = qStates.superPos(2, excitations=[0,1])
superPosState1Array = qStates.superPos(2, excitations=[0,1], sparse=False)
# sqrt(0.2) at 0th and sqrt(0.8) at 1st element of the column matrix, i.e. population of 0 is 0.2, and population of 1 is 0.8
superPosState2Sparse = qStates.superPos(2, {0:0.2, 1:0.8})
superPosState2Array = qStates.superPos(2, {0:0.2, 1:0.8}, sparse=False)

print('Ket States')
print(superPosState0Sparse)
print(superPosState0Sparse.A)
print(superPosState0Array)
print('Equal Super-position')
print(superPosState1Sparse)
print(superPosState1Array)
print(superPosState1Array[0]**2)
print(superPosState1Array[1]**2)
print('Super-position of given populations (keys of the dict)')
print(superPosState2Sparse)
print(superPosState2Sparse.A)
print(superPosState2Array)
print(superPosState2Array[0]**2)
print(superPosState2Array[1]**2)

Ket States
  (1, 0)	1.0
[[0.]
 [1.]]
[[0.]
 [1.]]
Equal Super-position
  (0, 0)	0.7071067811865475
  (1, 0)	0.7071067811865475
[[0.70710678]
 [0.70710678]]
[0.5]
[0.5]
Super-position of given populations (keys of the dict)
  (0, 0)	0.44721359549995804
  (1, 0)	0.8944271909999161
[[0.4472136 ]
 [0.89442719]]
[[0.4472136 ]
 [0.89442719]]
[0.2]
[0.8]


## densityMatrix
---
This is a method to create a density matrix for a given ket (or pure) state.

In [8]:
# density matrices of the super-position states created above. It creates sparse/array structure.
densityMat2Sparse = qStates.densityMatrix(ket=superPosState2Sparse)
densityMat2Array = qStates.densityMatrix(superPosState2Array)

print('Sparse density matrix from a given sparse ket and array (.A) from the sparse density matrix')
print(densityMat2Sparse)
print(densityMat2Sparse.A)
print('Array density matrix from a given array ket')
print(densityMat2Array)

Sparse density matrix from a given sparse ket and array (.A) from the sparse density matrix
  (1, 0)	0.4000000000000002
  (0, 0)	0.2000000000000001
  (1, 1)	0.8000000000000004
  (0, 1)	0.4000000000000002
[[0.2 0.4]
 [0.4 0.8]]
Array density matrix from a given array ket
[[0.2 0.4]
 [0.4 0.8]]


## completeBasisMat
---
This is a method to convert a complete basis of ket states to density matrices or create a complete basis of density matrices for a given dimension.
Note: This is not a complete basis for n-by-n matrices but for populations, i.e. diagonals.

In [9]:
completeBasisSparse = qStates.completeBasis(2)
completeBasisArray = qStates.completeBasis(2, sparse=False)

completeBasisMat0Sparse = qStates.completeBasisMat(compKetBase=completeBasisSparse)
completeBasisMat1Array = qStates.completeBasisMat(compKetBase=completeBasisArray)

completeBasisMat01Sparse = qStates.completeBasisMat(dimension=2)
completeBasisMat11Array = qStates.completeBasisMat(dimension=2, sparse=False)

print('(Sparse) Matrix basis from given (sparse) ket basis')
for state in completeBasisMat0Sparse:
    print(state)
    print(state.A)
print('(Array) Matrix basis from given (array) ket basis')
for state in completeBasisMat1Array:
    print(state)
print('(Sparse) Matrix basis from given dimension by sparse=True (default)')
for state in completeBasisMat01Sparse:
    print(state)
    print(state.A)
print('(Array) Matrix basis from given dimension by sparse=False')
for state in completeBasisMat11Array:
    print(state)

(Sparse) Matrix basis from given (sparse) ket basis
  (0, 0)	1
[[1 0]
 [0 0]]
  (1, 1)	1
[[0 0]
 [0 1]]
(Array) Matrix basis from given (array) ket basis
[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
(Sparse) Matrix basis from given dimension by sparse=True (default)
  (0, 0)	1
[[1 0]
 [0 0]]
  (1, 1)	1
[[0 0]
 [0 1]]
(Array) Matrix basis from given dimension by sparse=False
[[1 0]
 [0 0]]
[[0 0]
 [0 1]]


## normalise  -  normaliseKet  -  normaliseMat
---
normalise a method to normalise any given state. This method checks and if-else and calls either normaliseKet and normaliseMat.

normaliseKet and normaliseMat are normalisation methods respectively for a ket state and density matrix.

In [10]:
import numpy as np
# create a non-normalised ket and density matrix
nonNormalisedKet = np.sqrt(0.2)*qStates.basis(2,1) + np.sqrt(0.8)*qStates.basis(2,0)
nonNormalisedDenMat = qStates.densityMatrix(nonNormalisedKet)

# normalise these states

# normalisedKet = qStates.normaliseKet(ket=nonNormalisedKet)
normalisedKet = qStates.normalise(state=nonNormalisedKet)

#normalisedDenMat = qStates.normaliseMat(denMat=nonNormalisedDenMat)
normalisedDenMat = qStates.normalise(nonNormalisedDenMat)

print(nonNormalisedKet.A)
print(nonNormalisedDenMat.A)
print(normalisedKet.A)
print(normalisedDenMat.A)

# see the populations in 1 and 0
print(normalisedKet[0]**2)
print(normalisedKet[1]**2)

[[0.89442719]
 [0.4472136 ]]
[[0.8 0.4]
 [0.4 0.2]]
[[0.89442719]
 [0.4472136 ]]
[[0.8 0.4]
 [0.4 0.2]]
  (0, 0)	0.8000000000000004
  (0, 0)	0.2000000000000001


## compositeState
---
This is a method to create ket state for a composite quantum system from a given list of sub-system dimensions and a list state informations.

This method can create super-position for a sub-state, so the list of state information can be a list of mixtures of int, list, and dict. (see superPos above to see how these are used)

In [11]:
# composite states for two (qubit) 2D systems

# super-position state where first sub-system is in state 0 and second is in 1
compositeState0 = qStates.compositeState(dimensions=[2, 2], excitations=[0,1], sparse=True)

# super-position state where first sub-system is in equal super-position of 0&1 and second is in 1
compositeState1 = qStates.compositeState(dimensions=[2, 2], excitations=[[0,1],1], sparse=True)

# super-position state where first sub-system is in state 0 and second is in a super-position with 0.2 population in 0 and 0.8 in 1
compositeState2 = qStates.compositeState(dimensions=[2, 2], excitations=[0,{0:0.2, 1:0.8}], sparse=True)

print(compositeState0.A)
print(compositeState1.A)
print(compositeState2.A)

# above prints are not very instructive, so let's see the next tool, partialTrace.

[[0]
 [1]
 [0]
 [0]]
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]]
[[0.4472136 ]
 [0.89442719]
 [0.        ]
 [0.        ]]


## tensorProd
---
This is a method to calculate tensor product of given states (in the given order).

## partialTrace
---
This is a method to take partial trace to trace-out some of the sub-systems.

Note: This function CANNOT keep sparse structure, i.e. always returns an array

In [12]:
# partial traces of the composite states above.
stateFirstSystem0 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState0)
stateSecondSystem0 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState0)

stateFirstSystem1 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState1)
stateSecondSystem1 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState1)

stateFirstSystem2 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState2)
stateSecondSystem2 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState2)

# print and see the states of the first sub-system in each composite state
print('States of first sub-system')
print(stateFirstSystem0)
print(stateFirstSystem1)
print(stateFirstSystem2)

# print and see the states of the second sub-system in each composite state
print('States of second sub-system')
print(stateSecondSystem0)
print(stateSecondSystem1)
print(stateSecondSystem2)

States of first sub-system
[[1 0]
 [0 0]]
[[0.5 0.5]
 [0.5 0.5]]
[[1. 0.]
 [0. 0.]]
States of second sub-system
[[0 0]
 [0 1]]
[[0. 0.]
 [0. 1.]]
[[0.2 0.4]
 [0.4 0.8]]


## mat2Vec
---
This is a method to convert density matrix into density vector, which is used in super-operator representation for open-systems.

In [14]:
# create a ket state and calculate the density matrix
denMat = qStates.densityMatrix(ket=qStates.basis(dimension=2, state=1, sparse=True))

# convert it into density vector
denVec = qStates.mat2Vec(denMat=denMat.A)

print(denMat.A)
print(denVec)

[[0 0]
 [0 1]]
[[0]
 [0]
 [0]
 [1]]


## vec2mat
---
This is a method to convert density vector into density matrix.

In [15]:
# convert above density vector back into the density matrix.
denMatConverted = qStates.vec2mat(vec=denVec)

print(denMatConverted)

[[0 0]
 [0 1]]
