In [1]:
import qTools.QuantumToolbox.operators as qOperators

# How-to-use functions in operators.py of QuantumToolbox
---

Each example is introduced in the order that they appear inside the file

In [2]:
# Uncomment any (or both) of these two to print module docstrings
#print(qOperators.__doc__)
#help(qOperators)

## number
---
This is a method to create (bosonic) number operator for a given dimension.

In [5]:
# sparse=True by default
# for dimension 3
numberArray = qOperators.number(N=3, sparse=False)
numberSparse = qOperators.number(3)

print(numberArray)
# You obtain the array by simply calling .A on the sparse matrix
# If sparse=True, function simply returns state.A
# so, these two are equivalent, and I will create sparse and use .A in the rest of this example to print array
print(numberSparse.A)
print(numberArray)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
[[0 0 0]
 [0 1 0]
 [0 0 2]]
[[0 0 0]
 [0 1 0]
 [0 0 2]]


## destroy
---
This is a method to create (bosonic) annihilation operator for a given dimension.

In [6]:
# for dimension 2 and 1 at 1st element of the row matrix (see the print below)
annihilation = qOperators.destroy(N=3)
annihilation = qOperators.destroy(3)

print(annihilation)
print(annihilation.A)

(0, 1)	1.0
  (1, 2)	1.4142135623730951
[[0.         1.         0.        ]
 [0.         0.         1.41421356]
 [0.         0.         0.        ]]


## create
---
This is a method to create (bosonic) creation operator for a given dimension.

In [8]:
# for dimension 2 and all the elements of the column matrix are 0 (see the print below)
create = qOperators.create(3)

print(create)
print(create.A)

(1, 0)	1.0
  (2, 1)	1.4142135623730951
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.41421356 0.        ]]


## identity
---
This is a method to create an identity operator for a given dimension.

In [9]:
identity = qOperators.identity(3)

print(identity.A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## densityMatrix
---
This is a method to create a density matrix for a given ket (or pure) state.

In [ ]:
# density matrices of the super-position states created above
densityMat1 = qStates.densityMatrix(ket=superPosState1)
densityMat2 = qStates.densityMatrix(superPosState2)

print(densityMat1.A)
print(densityMat2.A)

## normalise  -  normaliseKet  -  normaliseMat
---
normalise a method to normalise any given state. This method checks and if-else and calls either normaliseKet and normaliseMat.

normaliseKet and normaliseMat are normalisation methods respectively for a ket state and density matrix.

In [ ]:
import numpy as np
# create a non-normalised ket and density matrix
nonNormalisedKet = np.sqrt(0.2)*qStates.basis(2,1) + np.sqrt(0.8)*qStates.basis(2,0)
nonNormalisedDenMat = qStates.densityMatrix(nonNormalisedKet)

# normalise these states

# normalisedKet = qStates.normaliseKet(ket=nonNormalisedKet)
normalisedKet = qStates.normalise(state=nonNormalisedKet)

#normalisedDenMat = qStates.normaliseMat(denMat=nonNormalisedDenMat)
normalisedDenMat = qStates.normalise(nonNormalisedDenMat)

print(nonNormalisedKet.A)
print(nonNormalisedDenMat.A)
print(normalisedKet.A)
print(normalisedDenMat.A)

# see the populations in 1 and 0
print(normalisedKet[0]**2)
print(normalisedKet[1]**2)

## compositeState
---
This is a method to create ket state for a composite quantum system from a given list of sub-system dimensions and a list state informations.

This method can create super-position for a sub-state, so the list of state information can be a list of mixtures of int, list, and dict. (see superPos above to see how these are used)

In [ ]:
# composite states for two (qubit) 2D systems

# super-position state where first sub-system is in state 0 and second is in 1
compositeState0 = qStates.compositeState(dimensions=[2, 2], excitations=[0,1], sparse=True)

# super-position state where first sub-system is in equal super-position of 0&1 and second is in 1
compositeState1 = qStates.compositeState(dimensions=[2, 2], excitations=[[0,1],1], sparse=True)

# super-position state where first sub-system is in state 0 and second is in a super-position with 0.2 population in 0 and 0.8 in 1
compositeState2 = qStates.compositeState(dimensions=[2, 2], excitations=[0,{0:0.2, 1:0.8}], sparse=True)

print(compositeState0.A)
print(compositeState1.A)
print(compositeState2.A)

# above prints are not very instructive, so let's see the next tool, partialTrace.

## partialTrace
---
This is a method to take partial trace to trace-out some of the sub-systems.

Note: This function CANNOT keep sparse structure, i.e. always returns an array

In [ ]:
# partial traces of the composite states above.
stateFirstSystem0 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState0)
stateSecondSystem0 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState0)

stateFirstSystem1 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState1)
stateSecondSystem1 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState1)

stateFirstSystem2 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState2)
stateSecondSystem2 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState2)

# print and see the states of the first sub-system in each composite state
print('States of first sub-system')
print(stateFirstSystem0)
print(stateFirstSystem1)
print(stateFirstSystem2)

# print and see the states of the second sub-system in each composite state
print('States of second sub-system')
print(stateSecondSystem0)
print(stateSecondSystem1)
print(stateSecondSystem2)

## mat2Vec
---
This is a method to convert density matrix into density vector, which is used in super-operator representation for open-systems.

In [ ]:
# create a ket state and calculate the density matrix
denMat = qStates.densityMatrix(ket=qStates.basis(dimension=2, state=1, sparse=True))

# convert it into density vector
denVec = qStates.mat2Vec(densityMatrix=denMat)

print(denMat.A)
print(denVec.A)

## vec2mat
---
This is a method to convert density vector into density matrix.

In [ ]:
# convert above density vector back into the density matrix.
denMatConverted = qStates.vec2mat(vec=denVec)

print(denMatConverted.A)