In [1]:
import qTools.QuantumToolbox.states as qStates

# How-to-use functions in states.py of QuantumToolbox
---

Each example is introduced in the order that they appear inside the file

In [2]:
# Uncomment any (or both) of these two to print module docstrings
#print(qStates.__doc__)
#help(qStates)

## basis
---
This is a method to create ket states for a given dimension.

In [3]:
# sparse=True by default
# for dimension 2 and 1 at 0th element of the column matrix (see the print below)
ketStateSparse = qStates.basis(dimension=2, state=0)
ketStateArray = qStates.basis(2, 0, sparse=False)

print(ketStateSparse)
# You obtain the array by simply calling .A on the sparse matrix
# If sparse=True, function simply returns state.A
# so, these two are equivalent, and I will create sparse and use .A in the rest of this example to print array
print(ketStateSparse.A)
print(ketStateArray)

(0, 0)	1
[[1]
 [0]]
[[1]
 [0]]


## basisBra
---
This is a method to create bra states for a given dimension.

In [4]:
# for dimension 2 and 1 at 1st element of the row matrix (see the print below)
braState = qStates.basisBra(dimension=2, state=1)
braState = qStates.basisBra(2, 1)

print(braState)
print(braState.A)

(0, 1)	1
[[0 1]]


## zeros
---
This is a method to create a column matrix of zeros for a given dimension.

In [5]:
# for dimension 2 and all the elements of the column matrix are 0 (see the print below)
zeros = qStates.zeros(dimension=2)
zeros = qStates.zeros(2)

print(zeros)
print(zeros.A)

(0, 0)	0
[[0]
 [0]]


## superPos
---
This is a method to create a super-position state for a given dimension.
Depending on the second argument, this returns:

1) int: equivalent to basis, i.e. returns a ket state with a unit population at the given int 

2) list: creates an equally populated super-position state from a list of integers

3) dict: creates a super-position by using the key as state int and the value as population

In [6]:
# 1 at 0th element of the column matrix (see the print below)
superPosState0 = qStates.superPos(dimension=2, excitations=1, sparse=True)
# sqrt(0.5) at 0th and 1st elements of the column matrix, i.e. population of each state is 0.5
superPosState1 = qStates.superPos(2, excitations=[0,1])
# sqrt(0.2) at 0th and sqrt(0.8) at 1st element of the column matrix, i.e. population of 0 is 0.2, and population of 1 is 0.8
superPosState2 = qStates.superPos(2, {0:0.2, 1:0.8})

print(superPosState0)
print(superPosState1.A)
print(superPosState1[0]**2)
print(superPosState1[1]**2)
print(superPosState2.A)
print(superPosState2[0]**2)
print(superPosState2[1]**2)

(1, 0)	1.0
[[0.70710678]
 [0.70710678]]
  (0, 0)	0.4999999999999999
  (0, 0)	0.4999999999999999
[[0.4472136 ]
 [0.89442719]]
  (0, 0)	0.2000000000000001
  (0, 0)	0.8000000000000004


## densityMatrix
---
This is a method to create a density matrix for a given ket (or pure) state.

In [7]:
# density matrices of the super-position states created above
densityMat1 = qStates.densityMatrix(ket=superPosState1)
densityMat2 = qStates.densityMatrix(superPosState2)

print(densityMat1.A)
print(densityMat2.A)

[[0.5 0.5]
 [0.5 0.5]]
[[0.2 0.4]
 [0.4 0.8]]


## normalise  -  normaliseKet  -  normaliseMat
---
normalise a method to normalise any given state. This method checks and if-else and calls either normaliseKet and normaliseMat.

normaliseKet and normaliseMat are normalisation methods respectively for a ket state and density matrix.

In [8]:
import numpy as np
# create a non-normalised ket and density matrix
nonNormalisedKet = np.sqrt(0.2)*qStates.basis(2,1) + np.sqrt(0.8)*qStates.basis(2,0)
nonNormalisedDenMat = qStates.densityMatrix(nonNormalisedKet)

# normalise these states

# normalisedKet = qStates.normaliseKet(ket=nonNormalisedKet)
normalisedKet = qStates.normalise(state=nonNormalisedKet)

#normalisedDenMat = qStates.normaliseMat(denMat=nonNormalisedDenMat)
normalisedDenMat = qStates.normalise(nonNormalisedDenMat)

print(nonNormalisedKet.A)
print(nonNormalisedDenMat.A)
print(normalisedKet.A)
print(normalisedDenMat.A)

# see the populations in 1 and 0
print(normalisedKet[0]**2)
print(normalisedKet[1]**2)

[[0.89442719]
 [0.4472136 ]]
[[0.8 0.4]
 [0.4 0.2]]
[[0.89442719]
 [0.4472136 ]]
[[0.8 0.4]
 [0.4 0.2]]
  (0, 0)	0.8000000000000004
  (0, 0)	0.2000000000000001


## compositeState
---
This is a method to create ket state for a composite quantum system from a given list of sub-system dimensions and a list state informations.

This method can create super-position for a sub-state, so the list of state information can be a list of mixtures of int, list, and dict. (see superPos above to see how these are used)

In [9]:
# composite states for two (qubit) 2D systems

# super-position state where first sub-system is in state 0 and second is in 1
compositeState0 = qStates.compositeState(dimensions=[2, 2], excitations=[0,1], sparse=True)

# super-position state where first sub-system is in equal super-position of 0&1 and second is in 1
compositeState1 = qStates.compositeState(dimensions=[2, 2], excitations=[[0,1],1], sparse=True)

# super-position state where first sub-system is in state 0 and second is in a super-position with 0.2 population in 0 and 0.8 in 1
compositeState2 = qStates.compositeState(dimensions=[2, 2], excitations=[0,{0:0.2, 1:0.8}], sparse=True)

print(compositeState0.A)
print(compositeState1.A)
print(compositeState2.A)

# above prints are not very instructive, so let's see the next tool, partialTrace.

[[0]
 [1]
 [0]
 [0]]
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]]
[[0.4472136 ]
 [0.89442719]
 [0.        ]
 [0.        ]]


## partialTrace
---
This is a method to take partial trace to trace-out some of the sub-systems.

Note: This function CANNOT keep sparse structure, i.e. always returns an array

In [12]:
# partial traces of the composite states above.
stateFirstSystem0 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState0)
stateSecondSystem0 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState0)

stateFirstSystem1 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState1)
stateSecondSystem1 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState1)

stateFirstSystem2 = qStates.partialTrace(keep=[0], dims=[2, 2], state=compositeState2)
stateSecondSystem2 = qStates.partialTrace(keep=[1], dims=[2, 2], state=compositeState2)

# print and see the states of the first sub-system in each composite state
print('States of first sub-system')
print(stateFirstSystem0)
print(stateFirstSystem1)
print(stateFirstSystem2)

# print and see the states of the second sub-system in each composite state
print('States of second sub-system')
print(stateSecondSystem0)
print(stateSecondSystem1)
print(stateSecondSystem2)

States of first sub-system
[[1 0]
 [0 0]]
[[0.5 0.5]
 [0.5 0.5]]
[[1. 0.]
 [0. 0.]]
States of second sub-system
[[0 0]
 [0 1]]
[[0. 0.]
 [0. 1.]]
[[0.2 0.4]
 [0.4 0.8]]


## mat2Vec
---
This is a method to convert density matrix into density vector, which is used in super-operator representation for open-systems.

In [13]:
# create a ket state and calculate the density matrix
denMat = qStates.densityMatrix(ket=qStates.basis(dimension=2, state=1, sparse=True))

# convert it into density vector
denVec = qStates.mat2Vec(densityMatrix=denMat)

print(denMat.A)
print(denVec.A)

[[0 0]
 [0 1]]
[[0]
 [0]
 [0]
 [1]]


## vec2mat
---
This is a method to convert density vector into density matrix.

In [14]:
# convert above density vector back into the density matrix.
denMatConverted = qStates.vec2mat(vec=denVec)

print(denMatConverted.A)

[[0 0]
 [0 1]]
