In [1]:
import qTools.QuantumToolbox.operators as qOperators

# How-to-use functions in operators.py of QuantumToolbox
---

Each example is introduced in the order that they appear inside the file

In [2]:
# Uncomment any (or both) of these two to print module docstrings
print(qOperators.__doc__)
help(qOperators)

]]
        >>> jx0 = Jx(j=2, isDim=False)
        (1, 0)      1.0
        (0, 1)      1.0
        (2, 1)      1.224744871391589
        (1, 2)      1.224744871391589
        (3, 2)      1.224744871391589
        (2, 3)      1.224744871391589
        (4, 3)      1.0
        (3, 4)      1.0
        >>> jx1 = Jx(j=5, sparse=False)
        [[0.         1.         0.         0.         0.        ]
        [1.         0.         1.22474487 0.         0.        ]
        [0.         1.22474487 0.         1.22474487 0.        ]
        [0.         0.         1.22474487 0.         1.        ]
        [0.         0.         0.         1.         0.        ]]
        >>> jx1 = Jx(j=5, isDim=True)
        (1, 0)      1.0
        (0, 1)      1.0
        (2, 1)      1.224744871391589
        (1, 2)      1.224744871391589
        (3, 2)      1.224744871391589
        (2, 3)      1.224744871391589
        (4, 3)      1.0
        (3, 4)      1.0
    
    Jy(j: float, sparse: bool = True, isDim: bool = 

# Bosonic Operators
---

## number
This is a method to create (bosonic) number ($\hat{n}$) operator for a given dimension.

In [ ]:
# sparse=True by default
# for dimension 3
numberArray = qOperators.number(dimension=3)
numberSparse = qOperators.number(3)

print(numberSparse)
# You obtain the array by simply calling .A on the sparse matrix
# If sparse=True, function simply returns state.A
# so, these two are equivalent, and I will create sparse and use .A in the rest of this example to print array
print(numberSparse.A)
print(numberArray)

## destroy
---
This is a method to create (bosonic) annihilation operator for a given dimension.

In [ ]:
# for dimension 3
annihilation = qOperators.destroy(dimension=3)
annihilation = qOperators.destroy(3)

print(annihilation)
print(annihilation.A)

## create ($ \hat{a}^{\dagger}$)
---
This is a method to create (bosonic) creation operator for a given dimension.

In [ ]:
# for dimension 3
create = qOperators.create(3)

print(create)
print(create.A)

# identity
---
This is a method to create an identity operator for a given dimension.

In [ ]:
# for dimension 3
identity = qOperators.identity(3)

print(identity)
print(identity.A)

# Pauli matrices (Qubit operators)
---

## Sigma Z
This is a method to create Pauli Z operator.

In [ ]:
sz = qOperators.sigmaz(sparse=False)
sz = qOperators.sigmaz()

print(sz.A)
print(sz)

## Sigma Y
---

This is a method to create Pauli Y operator.

In [ ]:
sy = qOperators.sigmay(sparse=False)
sy = qOperators.sigmay()

print(sy.A)
print(sy)

## Sigma X
---

This is a method to create Pauli X operator.

In [ ]:
sx = qOperators.sigmax(sparse=False)
sx = qOperators.sigmax()

print(sx.A)
print(sx)

## Sigma +
---

This is a method to create Pauli + (creation) operator.

In [ ]:
sp = qOperators.sigmap(sparse=False)
sp = qOperators.sigmap()

print(sp.A)
print(sp)

## Sigma -
---

This is a method to create Pauli - (destruction) operator.

In [ ]:
sm = qOperators.sigmam(sparse=False)
sm = qOperators.sigmam()

print(sm.A)
print(sm)

# Spin Operators
---

These are spin operator for a given dimension or the corresponding spin quantum number (j, whic is an integer (boson) or half-integer (fermion)).

Pauli matrices are j = 0.5 special case of these.

## Jz
This is a method to create spin Z operator for a given dimension or the corresponding spin quatum number.

All the below examples are for dimension 5 (spin quantum number = 2).

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
jz0 = qOperators.Jz(j=2, isDim=False, sparse=False)
jz0 = qOperators.Jz(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
jz1 = qOperators.Jz(j=5, sparse=False)
jz1 = qOperators.Jz(j=5, isDim=True)

print(jz0)
print(jz0.A)
print(jz1)
print(jz1.A)

## Jp
This is a method to create a creation operator for a given dimension or the corresponding spin quatum number.

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
jp0 = qOperators.Jp(j=2, isDim=False, sparse=False)
jp0 = qOperators.Jp(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
jp1 = qOperators.Jp(j=5, sparse=False)
jp1 = qOperators.Jp(j=5, isDim=True)

print(jp0)
print(jp0.A)
print(jp1)
print(jp1.A)

## Jm
This is a method to create a destruction operator for a given dimension or the corresponding spin quatum number.

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
jm0 = qOperators.Jm(j=2, isDim=False, sparse=False)
jm0 = qOperators.Jm(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
jm1 = qOperators.Jm(j=5, sparse=False)
jm1 = qOperators.Jm(j=5, isDim=True)

print(jm0)
print(jm0.A)
print(jm1)
print(jm1.A)

## Jx
---

This is a method to create spin X operator for a given dimension or the corresponding spin quatum number.

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
jx0 = qOperators.Jx(j=2, isDim=False, sparse=False)
jx0 = qOperators.Jx(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
jx1 = qOperators.Jx(j=5, sparse=False)
jx1 = qOperators.Jx(j=5, isDim=True)

print(jx0)
print(jx0.A)
print(jx1)
print(jx1.A)

## Jy
---

This is a method to create spin Y operator for a given dimension or the corresponding spin quatum number.

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
jy0 = qOperators.Jy(j=2, isDim=False, sparse=False)
jy0 = qOperators.Jy(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
jy1 = qOperators.Jy(j=5, sparse=False)
jy1 = qOperators.Jy(j=5, isDim=True)

print(jy0)
print(jy0.A)
print(jy1)
print(jy1.A)

## Js
---

This is a method to create the total spin operator for a given dimension or the corresponding spin quatum number.

In [ ]:
# you can directly tell the spin quantum number by making isDim=False
js0 = qOperators.Js(j=2, isDim=False, sparse=False)
js0 = qOperators.Js(j=2, isDim=False)

# or tell just tell dimension (= (2* spin quantum number) + 1) the dimension 
js1 = qOperators.Js(j=5, sparse=False)
js1 = qOperators.Js(j=5, isDim=True)

print(js0)
print(js0.A)
print(js1)
print(js1.A)

# Other Operators
---

These are method to create some EM-Field operators, Parity operator, and power of an operator.

operatorPow
---
This a function to create an operator raised to a power by using the function refence to the operator.

In [ ]:
# square of Pauli operators are identity, so the third power is the operator itself.
# let's use this function to calculate it for sigmax, so we pass the reference to sigmax as argument to the function.
squareSigmaX = qOperators.operatorPow(op=qOperators.sigmax, dim=2, power=2, sparse=False)
squareSigmaX = qOperators.operatorPow(op=qOperators.sigmax, dim=2, power=2)

cubedSigmaX = qOperators.operatorPow(op=qOperators.sigmax, dim=2, power=3, sparse=False)
cubedSigmaX = qOperators.operatorPow(op=qOperators.sigmax, dim=2, power=3)

print(squareSigmaX)
print(squareSigmaX.A)

print(cubedSigmaX)
print(cubedSigmaX.A)

paritySUM - parityEXP
---
These two are methods to create a Parity operator.

In [ ]:
# ParitySUM creates the parity operator by explicity placing alternating +/- into a matrix of given dimension.
paritySum = qOperators.paritySUM(dimension=5, sparse=False)
paritySum = qOperators.paritySUM(dimension=5)

# ParityEXP for 5 dimensional number operator by exponentiating int
ham = qOperators.number(dimension=5, sparse=False)
parityEXP = qOperators.parityEXP(HamiltonianCavity=ham) # returns an array since ham is an array

ham = qOperators.number(dimension=5)
parityEXP = qOperators.parityEXP(HamiltonianCavity=ham) # returns a sparse since ham is a sparse

print(paritySum)
print(paritySum.A)
print(parityEXP)
print(parityEXP.A)

## basis
---
This is a method to create ket states for a given dimension.

In [ ]:
# sparse=True by default
# for dimension 2 and 1 at 0th element of the column matrix (see the print below)
ketStateSparse = qOperators.basis(dimension=2, state=0)
ketStateArray = qOperators.basis(2, 0, sparse=False)

print(ketStateSparse)
print(ketStateSparse.A)
print(ketStateArray)

## displacement
---
This is a method to create the field-displacement operator for a given (truncation) dimension.

In [ ]:
# alpha is the displacement parameter
disp = qOperators.displacement(alpha=1j, dim=4, sparse=False)
disp = qOperators.displacement(alpha=1j, dim=4)

print(disp)
print(disp.A)

## squeeze
---
This is a method to create the field-squeezing operator for a given (truncation) dimension.

In [ ]:
# alpha is the squeezing parameter
squeeze = qOperators.squeeze(alpha=1j, dim=4, sparse=False)
squeeze = qOperators.squeeze(alpha=1j, dim=4)

print(squeeze)
print(squeeze.A)

## compositeOp
---
This is a method to create (extend the Hilbert space) operators of a sub-system in a composite system.

In [2]:
# takes the matrix of the relevant operator as input. dimB is the total dimension before the sub-system, and dimA is the after.
# create sigmaz of the first qubit in a two qubit composite system
szQ1 = qOperators.compositeOp(operator=qOperators.sigmaz(), dimB=0, dimA=2)

# create sigmaz of the second qubit in a two qubit composite system
szQ2 = qOperators.compositeOp(operator=qOperators.sigmaz(), dimB=2, dimA=0)

print(szQ1.A)
print(szQ2.A)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
